name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     # Set to true to not commit the changes
    - uses: actions/checkout@v2
    
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v2.0.0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
